# Docker Compose file for building and launching the Web Manager

# WARNING: This Dockerfile is not suitable for production use.

services:
  salt-api:
    image: saltastroops/salt-api
    env_file:
      - .env
    environment:
      - PROPOSALS_DIR=/proposals
      - MAPPING_TOOL_DIR=/mapping-tool
      - MAPPING_TOOL_LOG_DIR=/mapping-logs
      - MAPPING_TOOL_PIPT_DIR=/tmp/.PIPT
      - MAPPING_TOOL_JAVA_COMMAND=java
      - MAPPING_TOOL_PYTHON_INTERPRETER=python
      - MAPPING_TOOL_FINDER_CHART_TOOL=imephi
      - MAPPING_TOOL_IMAGE_CONVERSION_COMMAND=/usr/bin/convert
    ports:
      - ${PORT}:80
    restart: always
    volumes:
      - ${PROPOSALS_DIR}:/proposals
      - ${MAPPING_TOOL_LOG_DIR}:/mapping-logs
      - ${MAPPING_TOOL_DIR}:/mapping-tool
