# Docker Compose file for building and launching the Web Manager

# WARNING: This Dockerfile is not suitable for production use.

version: "3"

services:
  webmanager:
    build:
      context: .
    env_file:
      - .env
    environment:
      - PROPOSALS_DIR=/proposals
    ports:
      - 8001:80
    restart: always
    volumes:
      - ${PROPOSALS_DIR}:/proposals
