version: "3.5"
services:
  web-manager-frontend:
    container_name: web-manager-container # Container name
    build:
      context: . # Location of our Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:80 # Port mapping
