pipeline {
  agent any

  stages {
    stage("Build the Docker image") {
      steps {
        script {
          dockerImage = docker.build("salt-api:latest")
        }
      }
    }
    stage("Push the Docker image") {
      steps {
        script {
          with docker.registry("https://ukulinga.com", "docker-registry-credentials") {
            dockerImage.push()
          }
        }
      }
    }
  }
}
