pipeline {
  agent any

  stages {
    stage("Build the Docker image") {
      steps {
        script {
          dockerImage = docker.build("salt-api:dev")
        }
      }
    }
    stage("Push the Docker image") {
      steps {
        script {
          docker.withRegistry("${DOCKER_REGISTRY}", "docker-registry-credentials") {
            dockerImage.push()
          }
        }
      }
    }
  }
}
