package jenkins.tests

pipeline {
  agent {
    dockerfile {
      filename 'Dockerfile'
      dir 'jenkins'
      args '-v salt-api-venv:/venv -u 0:0'
    }
  }
  environment {
    DEV_ENV_FILE = credentials('salt-api-dev-env')
  }
  stages {
    stage("Run tests") {
      steps {
        sh './jenkins/run-tests.sh'
      }
    }
    stage("Build and push Docker image") {
      steps {
        sh "/usr/local/bin/docker --version"
        sh "docker --version"
      }
    }
  }
  post {
    always {
      cleanWs()
    }
  }
}
