package jenkins.tests
@Library('saao-shared-library') _

pipeline {
  agent {
    dockerfile {
      filename 'Dockerfile'
      dir 'jenkins/tests'
      args '-v salt-api-venv:/venv -u 0:0'
    }
  }
  environment {
    DEV_ENV_FILE = credentials('salt-api-dev-env')
  }
  stages {
    stage("Run tests") {
      steps {
        sh 'poetry export -f requirements.txt --output requirements.txt --without-hashes --with dev'
        script {
           saao.runPythonTests black: ['saltapi']
        }
      }
    }
    stage("Build and push Docker image") {
      steps {
        sh "/usr/local/bin/docker --version"
        sh "docker --version"
      }
    }
  }
  post {
    always {
      cleanWs()
    }
  }
}
