@Library('saao-shared-library') _

pipeline {
  agent any

  stages {
    stage('Perform linting and testing') {
      agent {
        dockerfile {
          filename 'Dockerfile'
          dir 'jenkins'
          args '-v saltapi-pipcache:/root/.cache -u 0:0'
        }
      }

      steps {
        sh 'poetry add --group=dev allure-pytest bandit black mypy pytest ruff'
        script {
          success = saao.runPythonTests(
                  'bandit': ['src'],
                  'black': ['src', 'tests'],
                  // 'mypy': ['src'],
                  // 'pytest': ['tests'],
                  'ruff': ['src', 'tests'],
                  'usePoetry': true
          )
          if (!success) {
            error('Linting and/or testing was unsuccessful.')
          }
        }
      }
    }
  }
}
