@Library('saao-shared-library') _

pipeline {
  agent any

  stages {
    stage('Perform linting and testing') {
      agent {
        dockerfile {
          filename 'Dockerfile'
          dir 'jenkins'
          args '-v saltapi-pipcache:/root/.cache/pypoetry -u 0:0'
        }
      }

      steps {
        sh '''
        poetry add --group=dev allure-pytest
        poetry install
        '''
        script {
          success = saao.runPythonTests(
                  'bandit': ['saltapi'],
                  'black': ['saltapi', 'tests'],
                  // 'mypy': ['saltapi'],
                  // 'pytest': ['tests'],
                  'ruff': ['saltapi', 'tests'],
                  'usePoetry': true
          )
          if (!success) {
            error('Linting and/or testing was unsuccessful.')
          }
        }
      }
    }
  }
}
