# Use the official NGINX image as the base
FROM nginx:1.23.1

# Copy the custom NGINX configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 (internally)
EXPOSE 80
