#-----------------------------------------------------------------------------------
# Adapted from https://github.com/marketplace/actions/install-poetry-action#testing
#-----------------------------------------------------------------------------------
name: Test

on: ["push", "pull_request"]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Set up Python environment
        id: setup-python
        run: echo "python-version=3.9" >> $GITHUB_OUTPUT
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction
      #----------------------------------------------
      #           clone test (mock) data
      #----------------------------------------------
      - name: Clone test data repository
        uses: actions/checkout@master
        with:
          repository: saltastroops/salt-testdata
          path: tests/salt-testdata
          token: ${{ secrets.ACCESS_TOKEN }}
      #----------------------------------------------
      #        run test suite
      #----------------------------------------------
      - name: Run tests
        env:
          TEST_DATA_DIR: tests/salt-testdata/salt-api/
          PROPOSALS_DIR: tests/
          SDB_DSN: ${{ secrets.SDB_DSN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          FRONTEND_URI: ''
          SMTP_SERVER: localhost:7777
          FROM_EMAIL: salthelp@example.com
          MAPPING_TOOL_DIR: tests/
          MAPPING_TOOL_JAR: saltapi/util.py
          MAPPING_TOOL_DATABASE_ACCESS_CONFIG: saltapi/util.py
          MAPPING_TOOL_LOG_DIR: tests/
          MAPPING_TOOL_PROPOSALS_DIR: tests/
          MAPPING_TOOL_API_KEY: ''
          MAPPING_TOOL_PIPT_DIR: ''
          MAPPING_TOOL_WEB_MANAGER_URL: 'https://www.example.com/web_manager/'
          MAPPING_TOOL_EPHEMERIS_URL: 'https://www.example.com/ephemerides.cgi'
          MAPPING_TOOL_JAVA_COMMAND: ''
          MAPPING_TOOL_PYTHON_INTERPRETER: ''
          MAPPING_TOOL_FINDER_CHART_TOOL: ''
          MAPPING_TOOL_IMAGE_CONVERSION_COMMAND: ''
          MAPPING_TOOL_MAILCHIMP_API_KEY: ''
          MAPPING_TOOL_MAILCHIMP_LIST_ID: ''
          MAPPING_TOOL_NO_REPLY_EMAIL: user@example.com
          MAPPING_TOOL_SUBMIT_EMAIL: user@example.com
          MAPPING_TOOL_SSDA_URL: ''
          MAPPING_TOOL_SSDA_PASSWORD: ''
          MAPPING_TOOL_SSDA_USERNAME: ''
          MAPPING_TOOL_SDB_URL: ''
          MAPPING_TOOL_SDB_PASSWORD: ''
          MAPPING_TOOL_SDB_USERNAME: ''
          FINDING_CHARTS_DIR: tests/
          TCS_ICD_URL: https://example.com
        run: |
          poetry run pytest --mock-db-data --db-data-dir tests/salt-testdata/salt-api/ -W ignore::pytest.PytestUnraisableExceptionWarning
      #----------------------------------------------
      #        linting
      #----------------------------------------------
      - name: Linting
        run: |
          poetry run black saltapi tests
          poetry run isort saltapi tests
          poetry run flake8 saltapi tests
          poetry run mypy saltapi
