#-----------------------------------------------------------------------------------
# Adapted from https://github.com/marketplace/actions/install-poetry-action#testing
#-----------------------------------------------------------------------------------
name: Test

on: ["push", "pull_request"]

env:
  PYTHON_VERSION: 3.9

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      #           clone test (mock) data
      #----------------------------------------------
      - name: Clone test data repository
        uses: actions/checkout@master
        with:
          repository: saltastroops/salt-testdata
          path: tests/salt-testdata
          token: ${{ secrets.ACCESS_TOKEN }}
      #----------------------------------------------
      #        run tox
      #----------------------------------------------
      - name: Run tests
        env:
          TEST_DATA_DIR: tests/salt-testdata/salt-api/
          PROPOSALS_DIR: tests/
          SDB_DSN: ${{ secrets.SDB_DSN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          FRONTEND_URI: ''
          SMTP_SERVER: localhost:7777
          FROM_EMAIL: salthelp@example.com
          MAPPING_TOOL_DIR: tests/
          MAPPING_TOOL_JAR: saltapi/util.py
          MAPPING_TOOL_DATABASE_ACCESS_CONFIG: saltapi/util.py
          MAPPING_TOOL_LOG_DIR: tests/
          MAPPING_TOOL_PROPOSALS_DIR: tests/
          MAPPING_TOOL_API_KEY: ''
          MAPPING_TOOL_PIPT_DIR: ''
          MAPPING_TOOL_WEB_MANAGER_URL: https://www.example.com/web_manager/
          MAPPING_TOOL_EPHEMERIS_URL: https://www.example.com/ephemerides.cgi
          MAPPING_TOOL_JAVA_COMMAND: ''
          MAPPING_TOOL_PYTHON_INTERPRETER: ''
          MAPPING_TOOL_FINDER_CHART_TOOL: ''
          MAPPING_TOOL_IMAGE_CONVERSION_COMMAND: ''
          MAPPING_TOOL_MAILCHIMP_API_KEY: ''
          MAPPING_TOOL_MAILCHIMP_LIST_ID: ''
          MAPPING_TOOL_NO_REPLY_EMAIL: user@example.com
          MAPPING_TOOL_SUBMIT_EMAIL: user@example.com
          MAPPING_TOOL_SSDA_URL: ''
          MAPPING_TOOL_SSDA_PASSWORD: ''
          MAPPING_TOOL_SSDA_USERNAME: ''
          MAPPING_TOOL_SDB_URL: ''
          MAPPING_TOOL_SDB_PASSWORD: ''
          MAPPING_TOOL_SDB_USERNAME: ''
          FINDING_CHARTS_DIR: tests/
          TCS_ICD_URL: https://www.example.com/
        run: |
          sudo apt-get update
          sudo apt-get install xvfb libfontconfig wkhtmltopdf
          poetry run tox
