name: Test

on: ["push", "pull_request"]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install packages
        run: npm install

      - name: Clone test data repository
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git clone https://${TOKEN}@github.com/saltastroops/salt-testdata cypress/salt-testdata

#      - name: Run Angular Tests
#        run: npm test -- --watch=false --browsers=ChromeHeadless

        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
        env:
          CYPRESS_apiUrl: 'http://127.0.0.1:8001'
          CYPRESS_recordHttpConfig: '{"mockFilesDirectory":"cypress/salt-testdata/web-manager/","mockIntercepts":true}'
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: |
          npx eslint -c .eslintrc.json
          npx prettier --check .
