name: Test

on: ["push", "pull_request"]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check out my other private repo
        run: cd ../../cypress/
        uses: actions/checkout@master
        with:
          repository: saltastroops/salt-testdata
          token: ${{ secrets.ACCESS_TOKEN }}
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          test: npm test -- --watch=false --browsers=ChromeHeadless
          run: |
          npx eslint -c .eslintrc.json
          npx prettier --check .
          start: npm start

        env:
          recordHttpConfig=: '{"mockFilesDirectory":"cypress/salt-testdata/web-manager/"}'
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
