name: Test

on: ["push", "pull_request"]

env:
  testdata_dir: cypress/salt-testdata

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install packages
        run: npm install

      - name: Clone test data repository
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git clone https://${TOKEN}@github.com/saltastroops/salt-testdata $testdata_dir

      - name: Run Angular Tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_apiUrl: "http://127.0.0.1:8001"
          CYPRESS_recordHttpConfig: '{"mockFilesDirectory":"$testdata_dir/web-manager/","mockIntercepts":true}'
          CYPRESS_grepTags: -@skip
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install: false
          start: npm start
          wait-on: "http://localhost:4200"

      - name: Lint
        run: |
          npx eslint -c .eslintrc.json
          npx prettier --check .
